[project]
name = "hexlet-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MrMeshka", email = "mrmeshas@gamail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
hexlet-pytest = "hexlet_pytest:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["hexlet_pytest"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
